SELECT 
    cast(productid as text) as productid,
    cast(name as text) as name,
    cast(productnumber as text) as productnumber,
    cast(makeflag as text) as makeflag,
    cast(finishedgoodsflag as text) as finishedgoodsflag,
    cast(color as text) as color,
    cast(safetystocklevel as text) as safetystocklevel,
    cast(reorderpoint as text) as reorderpoint,
    cast(standardcost as text) as standardcost,
    cast(listprice as text) as listprice,
    cast(size as text) as size,
    cast(sizeunitmeasurecode as text) as sizeunitmeasurecode,
    cast(weightunitmeasurecode as text) as weightunitmeasurecode,
    cast(weight as text) as weight,
    cast(daystomanufacture as text) as daystomanufacture,
    cast(productline as text) as productline,
    cast(class as text) as class,
    cast(style as text) as style,
    cast(productsubcategoryid as text) as productsubcategoryid,
    cast(productmodelid as text) as productmodelid,
    cast(sellstartdate as text) as sellstartdate,
    cast(sellenddate as text) as sellenddate,
    --cast(discontinueddate as text) as discontinueddate,
    cast(rowguid as text) as rowguid,
    cast(modifieddate as text) as modifieddate,
    cast(current_date as text) AS ingestion_date,
    'production.product' AS data_source,
    cast(session_user as text) AS current_user
FROM production.product;
